# Generated by Django 6.0.3 on 2026-03-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=150)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('custo', models.IntegerField()),
                ('tipo_receita', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'receita',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=120)),
                ('situacao', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
